import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Poppins } from "next/font/google";

const inter = Poppins({
  subsets: ["latin"],
  weight: "200",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
